### ISSUE TITLE
setup neighborhood centers

### ISSUE THREAD

**Issue by davidwhogg** [adrn/joaquin#10]
Possible algorithm:

1. kd-tree a subsample of stars
2. compute radius Rk to kth nearest neighbor for EVERY star in the subsample
3. choose smallest-Rk star as center number k=zero
4. increment k
4. choose the smallest-Rk star that is NOT a k-neighbor of any center prior to k as center k
5. goto 4.

**Comment by adrn** [comment]
Something like this is implemented now in `PCA-neighbors-apply.ipynb`!
