### ISSUE TITLE
PCA patching the spectra

### ISSUE THREAD

**Issue by adrn** [adrn/joaquin#3]
- Define the method
- Validate it!

**Comment by davidwhogg** [comment]
Here is the algorithm I suggest. I suggest we do this AFTER we subselect data down to the larger-neighborhood spectra but BEFORE the low-pass filter:

1. put ONES into the missing-data locations (or zeros if we are doing ln-flux)
2. compute the mean spectrum, save it, and subtract it from everything
3. compute a K=6-ish PCA of the mean-subtracted spectra.
4. replace the missing-data locations in the non-mean-subtraced data with the K=6-ish PCA approximations PLUS MEAN
6. goto 2.

Iterate 3-ish times or until convergence. Your choice!

**Comment by adrn** [comment]
We do this, but only one iterations worth!
